import os

code = ""
code += '"""OCT to RNFLT extraction endpoint.\n'
code += '\n'
code += 'POST /api/oct/extract-rnflt\n'
code += 'Accepts a raw OCT volume in MHA format.\n'
code += 'Returns RNFLT map, per-step stats, and Harvard-GD inference.\n'
code += '"""\n'
code += 'import base64\n'
code += 'import io\n'
code += 'import logging\n'
code += 'import os\n'
code += 'import uuid\n'
code += 'from pathlib import Path\n'
code += 'from typing import Any, Dict, Optional\n'
code += '\n'
code += 'import matplotlib\n'
code += 'matplotlib.use("Agg")\n'
code += 'import matplotlib.pyplot as plt\n'
code += 'import numpy as np\n'
code += 'from fastapi import APIRouter, File, HTTPException, UploadFile\n'
code += 'from fastapi.responses import JSONResponse\n'
code += '\n'
code += 'logger = logging.getLogger(__name__)\n'
code += '\n'
code += 'router = APIRouter(prefix="/oct", tags=["OCT RNFLT Extraction"])\n'
code += '\n'
code += 'UPLOAD_DIR = Path("data/processed/temp_uploads/mha")\n'
code += 'UPLOAD_DIR.mkdir(parents=True, exist_ok=True)\n'
code += 'DEBUG_DIR = Path("data/debug")\n'
code += 'DEBUG_DIR.mkdir(parents=True, exist_ok=True)\n'
code += '\n'
code += '\n'
code += 'def _rnflt_to_png_b64(rnflt_map: np.ndarray) -> str:\n'
code += '    fig, ax = plt.subplots(1, 1, figsize=(4, 4), dpi=100)\n'
code += '    im = ax.imshow(rnflt_map, cmap="turbo", interpolation="bilinear")\n'
code += '    ax.set_title("RNFL Thickness (um)", fontsize=9)\n'
code += '    ax.axis("off")\n'
code += '    plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04)\n'
code += '    buf = io.BytesIO()\n'
code += '    fig.savefig(buf, format="png", bbox_inches="tight", dpi=100)\n'
code += '    plt.close(fig)\n'
code += '    buf.seek(0)\n'
code += '    return base64.b64encode(buf.read()).decode("utf-8")\n'
code += '\n'
code += '\n'
code += '@router.post("/extract-rnflt")\n'
code += 'async def extract_rnflt_from_mha(\n'
code += '    file: UploadFile = File(...),\n'
code += ') -> JSONResponse:\n'
code += '    fname = file.filename or ""\n'
code += '    if not fname.lower().endswith(".mha"):\n'
code += '        raise HTTPException(status_code=400, detail="Only MHA files supported.")\n'
code += '    uid = str(uuid.uuid4())[:8]\n'
code += '    save_path = UPLOAD_DIR / f"{uid}_{fname}"\n'
code += '    content = await file.read()\n'
code += '    save_path.write_bytes(content)\n'
code += '    try:\n'
code += '        from ml.segmentation.oct_volume_reader import read_mha_from_bytes, volume_info\n'
code += '        volume, spacing = read_mha_from_bytes(content)\n'
code += '        info = volume_info(volume, spacing)\n'
code += '        from ml.segmentation.calibration import axial_um_per_voxel as aum_fn\n'
code += '        from ml.segmentation.thickness_calculator import compute_thickness_grid\n'
code += '        aum = aum_fn(spacing)\n'
code += '        thickness_grid, t_stats = compute_thickness_grid(volume, axial_um_per_voxel=aum)\n'
code += '        from ml.segmentation.rnflt_projector import project_to_rnflt_map\n'
code += '        rnflt_map, rnflt_meta = project_to_rnflt_map(thickness_grid)\n'
code += '        debug_path = DEBUG_DIR / f"rnflt_{uid}.npz"\n'
code += '        np.savez(str(debug_path), rnflt=rnflt_map, thickness_grid=thickness_grid)\n'
code += '        harvard: Dict[str, Any] = {}\n'
code += '        inf_err: Optional[str] = None\n'
code += '        try:\n'
code += '            from ml.models.inference import RNFLTInferenceEngine\n'
code += '            engine = RNFLTInferenceEngine(\n'
code += '                checkpoint_path="models/checkpoints/harvard_gd_rnflt_cnn_best.pt"\n'
code += '            )\n'
code += '            harvard = engine.predict(rnflt_map)\n'
code += '        except Exception as ex:\n'
code += '            inf_err = str(ex)\n'
code += '        png_b64 = _rnflt_to_png_b64(rnflt_map)\n'
code += '        return JSONResponse(content={\n'
code += '            "status": "success",\n'
code += '            "source_file": fname,\n'
code += '            "pipeline_steps": {\n'
code += '                "step_0_decode": {\n'
code += '                    "label": "OCT Volume Decoded",\n'
code += '                    "status": "complete",\n'
code += '                    "shape_zyx": list(info["shape_zyx"]),\n'
code += '                    "axial_um_per_voxel": info["axial_um_per_voxel"],\n'
code += '                    "num_bscans": info["num_bscans"],\n'
code += '                },\n'
code += '                "step_1_segmentation": {\n'
code += '                    "label": "RNFL Boundary Detection",\n'
code += '                    "status": "complete",\n'
code += '                    "method": "Classical graph-cut",\n'
code += '                    "b_scans_processed": int(thickness_grid.shape[0]),\n'
code += '                    "thickness_mean_um": float(t_stats["mean"]),\n'
code += '                    "thickness_min_um": float(t_stats["min"]),\n'
code += '                    "thickness_max_um": float(t_stats["max"]),\n'
code += '                },\n'
code += '                "step_2_rnflt_map": {\n'
code += '                    "label": "RNFLT Map Generated",\n'
code += '                    "status": "complete",\n'
code += '                    "shape": list(rnflt_map.shape),\n'
code += '                    "units": "um",\n'
code += '                    "min_um": rnflt_meta["min"],\n'
code += '                    "max_um": rnflt_meta["max"],\n'
code += '                    "mean_um": rnflt_meta["mean"],\n'
code += '                    "rnflt_map_png_b64": png_b64,\n'
code += '                },\n'
code += '                "step_3_harvard_gd": {\n'
code += '                    "label": "Harvard-GD Glaucoma Classification",\n'
code += '                    "status": "complete" if not inf_err else "error",\n'
code += '                    "result": harvard or None,\n'
code += '                    "error": inf_err,\n'
code += '                },\n'
code += '            },\n'
code += '            "rnflt_summary": {\n'
code += '                "shape": list(rnflt_map.shape),\n'
code += '                "dtype": str(rnflt_map.dtype),\n'
code += '                "units": "um",\n'
code += '                "min": rnflt_meta["min"],\n'
code += '                "max": rnflt_meta["max"],\n'
code += '                "mean": rnflt_meta["mean"],\n'
code += '                "median": rnflt_meta["median"],\n'
code += '                "std": rnflt_meta["std"],\n'
code += '            },\n'
code += '            "harvard_gd": harvard or None,\n'
code += '            "inference_error": inf_err,\n'
code += '            "disclaimer": (\n'
code += '                "RESEARCH-GRADE ESTIMATE ONLY. Graph-cut RNFL boundary detection. "\n'
code += '                "Physical calibration: 15.625 um/voxel. NOT a clinical device export. "\n'
code += '                "Not cleared by FDA/CE."\n'
code += '            ),\n'
code += '        })\n'
code += '    except HTTPException:\n'
code += '        raise\n'
code += '    except Exception as ex:\n'
code += '        logger.error("RNFLT extraction failed: %s", ex, exc_info=True)\n'
code += '        raise HTTPException(status_code=500, detail=f"RNFLT extraction failed: {ex}")\n'
code += '    finally:\n'
code += '        try:\n'
code += '            save_path.unlink(missing_ok=True)\n'
code += '        except Exception:\n'
code += '            pass\n'

with open('backend/app/api/endpoints/oct_rnflt_extract.py', 'w', encoding='utf-8') as f:
    f.write(code)
print('Written oct_rnflt_extract.py OK')
